// AUTO-GENERATED by tools/gen_kinds.js from nodes.js: DO NOT EDIT BY HAND.
// One row per kind, in SAVE-FORMAT order: NodeKind numbering is the save format,
// new kinds append at the end, reordering breaks saves. The registry (names,
// intervals, signal flags, these signatures) lives in nodes.js.
// Regenerate: node tools/gen_kinds.js   (bake.js runs it too)
#pragma once

#define LOUPE_NODE_KINDS(X) \
    X(NODE_NONE,        "none")      /* empty slot */ \
    X(NODE_LOOKUP,      "lookup")      /* (lookup tape ix) tape[ix mod len]: the shared selection core; reads CURRENT bytes, so a mutable scale hunts. step/seek are heads over it */ \
    X(NODE_TURNS,       "turns")      /* (turns [c]) clock c's running turn count on the value ring; (mod (turns) 4) = bar position */ \
    X(NODE_CONST,       "const")      /* a bare number: the constant stream (a literal operand for any two-stream op) */ \
    X(NODE_WAVE,        "wave")      /* (wave tape [pitch|:note N]) play a region as audio: wavetable osc / sample playback; :reverse :pos :once :slots/:pick :scan :interp */ \
    X(NODE_ARRANGE,     "arrange")      /* (arrange prog...) data-driven tape combiner: the order is DATA (huntable); :len slices, :advancing interweaves */ \
    X(NODE_COUNTER,     "counter")      /* (counter bar [:clock c]) bar number, +1 per clock tick (self-gating: catches up, never skips) */ \
    X(NODE_RANDOM,      "random")      /* (random [:shape s] [:clock c]) shaped random value, re-rolled per tick (seeded, reproducible) */ \
    X(NODE_CHANCE,      "chance")      /* (chance p [:clock c]) 0/VMAX with probability p/VMAX, re-rolled per tick */ \
    X(NODE_WALK,        "walk")      /* (walk [:step N] [:clock c]) drunken walk around centre */ \
    X(NODE_KNOB,        "knob")      /* (knob :name) a panel knob as a value */ \
    X(NODE_ACTIVE_PAGE, "active-page")      /* (active-page) the current page index */ \
    X(NODE_CV_IN,       "cv-in")      /* (cv-in N [:normal x]) CV input as a value */ \
    X(NODE_PULSE_IN,    "pulse-in")      /* (pulse-in N) pulse input as 0/VMAX */ \
    X(NODE_AUDIO_IN,    "audio-in")      /* (audio-in N) audio input, audio-rate signal */ \
    X(NODE_FROZEN,      "frozen")      /* (frozen tape-N) VMAX if the tape is frozen, else 0 */ \
    X(NODE_CONNECTED,   "connected")      /* (connected jack) VMAX if a cable is patched into that input jack */ \
    X(NODE_TRANSPOSE,   "transpose")      /* (transpose r N) add N, a literal or a STREAM (clamped); octave-correct on a note */ \
    X(NODE_INVERT,      "invert")      /* (invert r) VMAX - value */ \
    X(NODE_ADD,         "add")      /* (add a b) a + b, wraps on the value ring (:sat clamps); carries the signal domain */ \
    X(NODE_SUB,         "sub")      /* (sub a b) a - b, wraps on the value ring (:sat clamps); carries the signal domain */ \
    X(NODE_MUL,         "mul")      /* (mul a N) a * N saturating (gain); :wrap folds; :bipolar = ATTENUVERTER (centre=off, left inverts); a signal operand makes it a vca */ \
    X(NODE_DIV,         "div")      /* (div a N) a / N */ \
    X(NODE_MOD,         "mod")      /* (mod a N) a % N -> 0..N-1 (any N; bar/meter position) */ \
    X(NODE_SPREAD,      "spread")      /* (spread a N) (a * N) >> VBITS -> 0..N-1: spread a value across N buckets */ \
    X(NODE_SHIFT,       "shift")      /* (shift r N) offset a head's read by N positions (read into history) */ \
    X(NODE_XOR,         "xor")      /* (xor a b) bitwise; carries the signal domain (bit-mangled audio renders) */ \
    X(NODE_AND,         "and")      /* (and a b) bitwise; carries the signal domain */ \
    X(NODE_OR,          "or")      /* (or a b) bitwise; carries the signal domain */ \
    X(NODE_MASK,        "mask")      /* (mask r M) AND with a literal mask (bit-crush); carries the signal domain */ \
    X(NODE_BIT,         "bit")      /* (bit r N) extract bit N as 0/VMAX */ \
    X(NODE_GT,          "gt")      /* (gt a b) a > b -> VMAX/0 */ \
    X(NODE_GTE,         "gte")      /* (gte a b) a >= b -> VMAX/0 */ \
    X(NODE_LT,          "lt")      /* (lt a b) a < b -> VMAX/0 */ \
    X(NODE_LTE,         "lte")      /* (lte a b) a <= b -> VMAX/0 */ \
    X(NODE_EQ,          "eq")      /* (eq a b) a == b -> VMAX/0 */ \
    X(NODE_NE,          "ne")      /* (ne a b) a != b -> VMAX/0 */ \
    X(NODE_SWITCH,      "switch")      /* (switch sel r0 r1 ..) selector mod count picks a branch (splice = switch over a counter) */ \
    X(NODE_V_OCT,       "v-oct")      /* (v-oct note) emit a note value (0..127) as 1V/oct */ \
    X(NODE_CV,          "cv")      /* (cv r [:bipolar]) value -> linear unquantised voltage */ \
    X(NODE_GATE,        "gate")      /* (gate r trig|gate) threshold -> pulse (trig = floor width, gate = held) */ \
    X(NODE_ENVELOPE,    "envelope")      /* (envelope [:peak p] :trig|:gate src :decay d) decaying envelope; default trigger = the master beat */ \
    X(NODE_SLEW,        "slew")      /* (slew x N | :rate s) type-preserving smoother, rate literal or STREAM (portamento on a pitch signal) */ \
    X(NODE_AVERAGE,     "average")      /* (average sig cutoff) THE filter primitive: one-pole EMA; lpf/hpf/bpf/lpg are composition over it */ \
    X(NODE_SHAPE,       "shape")      /* (sine|triangle|saw|square X) a waveform over a phase: X = a note (fused phase) or a phasor; param = shape */ \
    X(NODE_RECORD,      "record")      /* the tape write: <- a stream into a tape sink (with :clock); the runtime write head */ \
    X(NODE_WAVEFOLD,    "wavefold")      /* (wavefold sig drive) anti-aliased (ADAA) triangle wavefolder */ \
    X(NODE_PHASOR,      "phasor")      /* (phasor :hz|:khz|:rate|:tempo|note) THE phase engine: a 32-bit ramp; clock_from = hard sync; every clock is one of these */ \
    X(NODE_EDGE,        "edge")      /* (edge x) rising edge of x -> a VMAX pulse */ \
    X(NODE_HOLD,        "hold")      /* (hold value trig) latch value on trig's rising edge (S&H; the audio->byte bridge) */ \
    X(NODE_DIFF,        "diff")      /* (diff x) x minus its previous value: the differentiator (slope), dual of the phasor */ \
    X(NODE_TOGGLE,      "toggle")      /* (toggle trig) T flip-flop: flips 0<->VMAX per rising edge (/2 divider) */ \
    X(NODE_SCHMITT,     "schmitt")      /* (schmitt x lo hi) comparator with hysteresis (clean triggering off noisy signals) */ \
    X(NODE_TAP,         "tap")      /* (tap tape N [:span] [:interp]) read N samples BEHIND the write head: the delay read (chorus/flanger/echo) */ \
    X(NODE_NOISE,       "noise")      /* (noise) audio-rate white noise (per-sample xorshift), bipolar */ \
    X(NODE_CRUSH,       "crush")      /* (crush x N) sample-RATE reducer (decimator); N is modulatable */ \
    X(NODE_VCF,         "vcf")      /* (vcf sig cutoff res) 2-pole resonant low-pass SVF; res up to self-oscillation */ \
    X(NODE_FOLLOW,      "follow")      /* (follow base :mult|:div N | :rate c [:drift d]) a DERIVED phasor in the phase domain (exact ratios re-cohere; drift bends) */ \
    X(NODE_VCLOCK,      "vclock")      /* (clock :times TAPE) variable-step clock: each step lasts a duration read from a time tape */ \
    X(NODE_TICK,        "tick")      /* (tick [c]) a one-sample VMAX pulse each time clock c completes a turn (the eurorack trigger) */ \
    X(NODE_SNAP,        "snap")      /* (snap note SCALE | :mask m) nearest note whose pitch-class is in the 12-bit MASK (bit k = class k); the mask is a value, so scales select/morph/hunt live */ \
    X(NODE_SWITCH_POS,  "switch-pos")      /* (switch-pos) the panel Z-switch: 0 down, 1 middle, 2 up (bare `switch-z`, ports :up/:middle/:down) */ \
    X(NODE_KICK,        "kick")      /* (kick [pitch] [:note N] [:decay d] [:drive g] [:sweep s] [:trig clk]) synthetic bass drum, the IDEA after Plaits (MIT, E. Gillet): pitch sweep + body decay + drive saturation, fixed-point & divide-free; all of pitch/decay/drive/sweep take a value or a stream */ \
    X(NODE_SNARE,       "snare")      /* (snare [pitch] [:note N] [:decay d] [:snappy s] [:tone t] [:trig clk]) snare drum, the IDEA after Plaits/808 (MIT, E. Gillet): two body modes + high-passed noise, blended by snappy; all of pitch/decay/snappy/tone take a value or a stream */ \
    X(NODE_HAT,         "hat")      /* (hat [pitch] [:note N] [:decay d] [:tone t] [:trig clk]) hi-hat / metallic percussion, the IDEA after Plaits/808 (MIT, E. Gillet): six inharmonic squares (from three phases) high-passed, fast decay */ \

