#!/usr/bin/env node
'use strict';
// Bake patches/hello.loupe into runtime/factory_snapshot.h.
// Run: node runtime/bake_factory.js

const fs   = require('node:fs');
const path = require('node:path');

const REPO      = path.resolve(__dirname, '..');
const LENS      = REPO;
const OUT_H     = path.join(__dirname, 'factory_snapshot.h');
const PATCH     = path.join(REPO, 'patches', 'hello.loupe');
const PRELUDE   = path.join(REPO, 'prelude.loupe');
const LENS_MAX  = 8192;

const { read }        = require(path.join(LENS, 'compiler', 'reader.js'));
const { expand }      = require(path.join(LENS, 'compiler', 'expander.js'));
const { lower }       = require(path.join(LENS, 'compiler', 'lowerer.js'));
const { schedule }    = require(path.join(LENS, 'compiler', 'scheduler.js'));
const { encode }      = require(path.join(LENS, 'compiler', 'snapshot.js'));

function makeLoader() {
  return relpath => fs.readFileSync(path.join(REPO, relpath), 'utf8');
}

const text     = fs.readFileSync(PATCH, 'utf8');
const ast      = read(text);
const expanded = expand(ast, { loadFile: makeLoader() });
const graph    = lower(expanded);
const sched    = schedule(graph);
const bytes    = encode(sched, graph);

if (bytes.length > LENS_MAX) {
  console.error(`factory snapshot too large: ${bytes.length} bytes (cap ${LENS_MAX})`);
  process.exit(1);
}

// Emit C header.
const cols  = 16;
const lines = [];
for (let i = 0; i < bytes.length; i += cols) {
  const chunk = Array.from(bytes.slice(i, i + cols))
    .map(b => `0x${b.toString(16).padStart(2, '0')}`)
    .join(', ');
  lines.push('    ' + chunk + ',');
}

const header = [
  '/* Generated by runtime/bake_factory.js -- do not edit by hand. */',
  '/* Source: patches/hello.loupe */',
  `/* ${bytes.length} bytes */`,
  '#pragma once',
  '#include <stdint.h>',
  `static const uint8_t lens_factory[${bytes.length}] = {`,
  lines.join('\n'),
  '};',
  `static const unsigned int lens_factory_len = ${bytes.length};`,
  '',
].join('\n');

fs.writeFileSync(OUT_H, header);
console.log(`factory_snapshot.h: ${bytes.length} bytes (cap ${LENS_MAX})`);
