#pragma once
#include <stdint.h>
/* DX7 algorithm routing table. Generated by tools/gen-fm-algorithms.js -- do not edit. */

struct FmAlgo {
    int8_t   order[6];      /* evaluation order, modulators before carriers */
    uint8_t  modmask[6];    /* 6-bit mask: which operators modulate this one */
    uint8_t  modcount[6];   /* popcount(modmask[op]) */
    uint8_t  carriers;      /* 6-bit mask of carrier operators */
    uint8_t  ncarriers;     /* number of carriers */
    int8_t   fbop;          /* 0-indexed self-feedback operator, or -1 */
};

static const struct FmAlgo FM_ALGOS[32] = {
    /* algo 1 */ { .order={1,0,5,4,3,2}, .modmask={2,0,8,16,32,0}, .modcount={1,0,1,1,1,0}, .carriers=5, .ncarriers=2, .fbop=5 },
    /* algo 2 */ { .order={1,0,5,4,3,2}, .modmask={2,0,8,16,32,0}, .modcount={1,0,1,1,1,0}, .carriers=5, .ncarriers=2, .fbop=1 },
    /* algo 3 */ { .order={2,1,0,5,4,3}, .modmask={2,4,0,16,32,0}, .modcount={1,1,0,1,1,0}, .carriers=9, .ncarriers=2, .fbop=5 },
    /* algo 4 */ { .order={2,1,0,5,4,3}, .modmask={2,4,0,16,32,0}, .modcount={1,1,0,1,1,0}, .carriers=9, .ncarriers=2, .fbop=5 },
    /* algo 5 */ { .order={1,0,3,2,5,4}, .modmask={2,0,8,0,32,0}, .modcount={1,0,1,0,1,0}, .carriers=21, .ncarriers=3, .fbop=5 },
    /* algo 6 */ { .order={1,0,3,2,5,4}, .modmask={2,0,8,0,32,0}, .modcount={1,0,1,0,1,0}, .carriers=21, .ncarriers=3, .fbop=5 },
    /* algo 7 */ { .order={1,0,3,5,4,2}, .modmask={2,0,24,0,32,0}, .modcount={1,0,2,0,1,0}, .carriers=5, .ncarriers=2, .fbop=5 },
    /* algo 8 */ { .order={1,0,3,5,4,2}, .modmask={2,0,24,0,32,0}, .modcount={1,0,2,0,1,0}, .carriers=5, .ncarriers=2, .fbop=3 },
    /* algo 9 */ { .order={1,0,3,5,4,2}, .modmask={2,0,24,0,32,0}, .modcount={1,0,2,0,1,0}, .carriers=5, .ncarriers=2, .fbop=1 },
    /* algo 10 */ { .order={2,1,0,4,5,3}, .modmask={2,4,0,48,0,0}, .modcount={1,1,0,2,0,0}, .carriers=9, .ncarriers=2, .fbop=2 },
    /* algo 11 */ { .order={2,1,0,4,5,3}, .modmask={2,4,0,48,0,0}, .modcount={1,1,0,2,0,0}, .carriers=9, .ncarriers=2, .fbop=5 },
    /* algo 12 */ { .order={1,0,3,4,5,2}, .modmask={2,0,56,0,0,0}, .modcount={1,0,3,0,0,0}, .carriers=5, .ncarriers=2, .fbop=1 },
    /* algo 13 */ { .order={1,0,3,4,5,2}, .modmask={2,0,56,0,0,0}, .modcount={1,0,3,0,0,0}, .carriers=5, .ncarriers=2, .fbop=5 },
    /* algo 14 */ { .order={1,0,4,5,3,2}, .modmask={2,0,8,48,0,0}, .modcount={1,0,1,2,0,0}, .carriers=5, .ncarriers=2, .fbop=5 },
    /* algo 15 */ { .order={1,0,4,5,3,2}, .modmask={2,0,8,48,0,0}, .modcount={1,0,1,2,0,0}, .carriers=5, .ncarriers=2, .fbop=1 },
    /* algo 16 */ { .order={1,3,2,5,4,0}, .modmask={22,0,8,0,32,0}, .modcount={3,0,1,0,1,0}, .carriers=1, .ncarriers=1, .fbop=5 },
    /* algo 17 */ { .order={1,3,2,5,4,0}, .modmask={22,0,8,0,32,0}, .modcount={3,0,1,0,1,0}, .carriers=1, .ncarriers=1, .fbop=1 },
    /* algo 18 */ { .order={1,2,5,4,3,0}, .modmask={14,0,0,16,32,0}, .modcount={3,0,0,1,1,0}, .carriers=1, .ncarriers=1, .fbop=2 },
    /* algo 19 */ { .order={2,1,0,5,3,4}, .modmask={2,4,0,32,32,0}, .modcount={1,1,0,1,1,0}, .carriers=25, .ncarriers=3, .fbop=5 },
    /* algo 20 */ { .order={2,0,1,4,5,3}, .modmask={4,4,0,48,0,0}, .modcount={1,1,0,2,0,0}, .carriers=11, .ncarriers=3, .fbop=2 },
    /* algo 21 */ { .order={2,0,1,5,3,4}, .modmask={4,4,0,32,32,0}, .modcount={1,1,0,1,1,0}, .carriers=27, .ncarriers=4, .fbop=2 },
    /* algo 22 */ { .order={1,0,5,2,3,4}, .modmask={2,0,32,32,32,0}, .modcount={1,0,1,1,1,0}, .carriers=29, .ncarriers=4, .fbop=5 },
    /* algo 23 */ { .order={0,2,1,5,3,4}, .modmask={0,4,0,32,32,0}, .modcount={0,1,0,1,1,0}, .carriers=27, .ncarriers=4, .fbop=5 },
    /* algo 24 */ { .order={0,1,5,2,3,4}, .modmask={0,0,32,32,32,0}, .modcount={0,0,1,1,1,0}, .carriers=31, .ncarriers=5, .fbop=5 },
    /* algo 25 */ { .order={0,1,2,5,3,4}, .modmask={0,0,0,32,32,0}, .modcount={0,0,0,1,1,0}, .carriers=31, .ncarriers=5, .fbop=5 },
    /* algo 26 */ { .order={0,2,1,4,5,3}, .modmask={0,4,0,48,0,0}, .modcount={0,1,0,2,0,0}, .carriers=11, .ncarriers=3, .fbop=5 },
    /* algo 27 */ { .order={0,2,1,4,5,3}, .modmask={0,4,0,48,0,0}, .modcount={0,1,0,2,0,0}, .carriers=11, .ncarriers=3, .fbop=2 },
    /* algo 28 */ { .order={1,0,4,3,2,5}, .modmask={2,0,8,16,0,0}, .modcount={1,0,1,1,0,0}, .carriers=37, .ncarriers=3, .fbop=4 },
    /* algo 29 */ { .order={0,1,3,2,5,4}, .modmask={0,0,8,0,32,0}, .modcount={0,0,1,0,1,0}, .carriers=23, .ncarriers=4, .fbop=5 },
    /* algo 30 */ { .order={0,1,4,3,2,5}, .modmask={0,0,8,16,0,0}, .modcount={0,0,1,1,0,0}, .carriers=39, .ncarriers=4, .fbop=4 },
    /* algo 31 */ { .order={0,1,2,3,5,4}, .modmask={0,0,0,0,32,0}, .modcount={0,0,0,0,1,0}, .carriers=31, .ncarriers=5, .fbop=5 },
    /* algo 32 */ { .order={0,1,2,3,4,5}, .modmask={0,0,0,0,0,0}, .modcount={0,0,0,0,0,0}, .carriers=63, .ncarriers=6, .fbop=5 },
};
