#!/usr/bin/env node
// bake.js — compile a .loupe patch into the firmware's embedded boot default.
//
//   node tools/bake.js [patches/meta-turing-machine.loupe]
//
// Outputs:
//   default_snapshot.h  flash-resident const uint8_t[]; applied at boot via ApplySnapshot.
//   factory.syx         ready-to-send WRITE_STATE SysEx message.
'use strict';
const fs = require('fs');
const path = require('path');
const { compilePatch, loadPatch, serializeSnapshot } = require('../compile.js');
const { CMD, frame } = require('../sysex.js');

// Regenerate node_kinds.h first so all generated artifacts stay in sync.
require('fs').writeFileSync(require('path').join(__dirname, '..', 'node_kinds.h'), require('./gen_kinds.js').render());

const root = path.join(__dirname, '..');
const src  = process.argv[2] || path.join(root, 'patches/meta-turing-machine.loupe');
const snapshot = serializeSnapshot(compilePatch(loadPatch(fs.readFileSync(src, 'utf8'), path.dirname(src))));
const rel  = path.relative(root, src);

const rows = [];
for (let i = 0; i < snapshot.length; i += 16)
  rows.push('  ' + [...snapshot.slice(i, i + 16)].map(b => String(b).padStart(3)).join(', ') + ',');
let h = '';
h += `// AUTO-GENERATED by tools/bake.js from ${rel} — DO NOT EDIT.\n`;
h += `// Regenerate:  node tools/bake.js ${rel}\n`;
h += '// The factory patch as a compact snapshot (snapshot.h), embedded in flash and applied\n';
h += '// at boot through the same ApplySnapshot path as any patch loaded over SysEx.\n';
h += '#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n';
h += 'namespace loupe {\n';
h += `static const uint8_t kDefaultSnapshot[] = {\n${rows.join('\n')}\n};\n`;
h += 'static const size_t kDefaultSnapshotLen = sizeof(kDefaultSnapshot);\n';
h += '}  // namespace loupe\n';
fs.writeFileSync(path.join(root, 'default_snapshot.h'), h);

fs.writeFileSync(path.join(root, 'factory.syx'), Buffer.from(frame(CMD.WRITE_STATE, snapshot)));

console.error(`baked ${rel}: ${snapshot.length} B snapshot -> default_snapshot.h + factory.syx`);
