#!/usr/bin/env node
// gen_kinds.js: generate node_kinds.h from nodes.js (single source of kind order). Called by bake.js.
'use strict';
const { NODES } = require('../nodes.js');

const sym = (name) => 'NODE_' + name.toUpperCase().replace(/-/g, '_');

function render() {
  const w = Math.max(...NODES.map(n => sym(n[0]).length));
  const rows = NODES.map(([name, , , sig]) =>
    `    X(${(sym(name) + ',').padEnd(w + 1)} "${name}")`.padEnd(w + 16 + name.length) +
    ` /* ${sig.replace(/\*\//g, '* /')} */ \\`);
  return `// AUTO-GENERATED by tools/gen_kinds.js from nodes.js: DO NOT EDIT BY HAND.
// One row per kind, in SAVE-FORMAT order: NodeKind numbering is the save format,
// new kinds append at the end, reordering breaks saves. The registry (names,
// intervals, signal flags, these signatures) lives in nodes.js.
// Regenerate: node tools/gen_kinds.js   (bake.js runs it too)
#pragma once

#define LOUPE_NODE_KINDS(X) \\
${rows.join('\n')}

`;
}

if (require.main === module) {
  const fs = require('fs'), path = require('path');
  const out = path.join(__dirname, '..', 'node_kinds.h');
  fs.writeFileSync(out, render());
  console.log(`generated node_kinds.h (${NODES.length} kinds)`);
}

module.exports = { render };
